on: [push]

jobs:
  load-test-sample:
    runs-on: ubuntu-latest
    name: A load test sample job
    steps:
    - uses: actions/checkout@master
    - name: Load Test action step
      id: load-test
      uses: ArtilleryGithubActions@master
      with:
        filepath: performance-test.yml
